import { Achievement } from '@/types/workout';

export const DEFAULT_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_workout',
    title: 'First Rep',
    description: 'Complete your first workout',
    icon: '💪',
    unlockedAt: null,
    requirement: 1,
    category: 'sessions',
  },
  {
    id: 'five_workouts',
    title: 'Getting Started',
    description: 'Complete 5 workouts',
    icon: '🔥',
    unlockedAt: null,
    requirement: 5,
    category: 'sessions',
  },
  {
    id: 'twenty_workouts',
    title: 'Dedicated',
    description: 'Complete 20 workouts',
    icon: '⚡',
    unlockedAt: null,
    requirement: 20,
    category: 'sessions',
  },
  {
    id: 'fifty_workouts',
    title: 'Iron Will',
    description: 'Complete 50 workouts',
    icon: '🏆',
    unlockedAt: null,
    requirement: 50,
    category: 'sessions',
  },
  {
    id: 'volume_10k',
    title: '10K Club',
    description: 'Lift 10,000 kg total volume',
    icon: '🪨',
    unlockedAt: null,
    requirement: 10000,
    category: 'volume',
  },
  {
    id: 'volume_100k',
    title: 'Centurion',
    description: 'Lift 100,000 kg total volume',
    icon: '🗿',
    unlockedAt: null,
    requirement: 100000,
    category: 'volume',
  },
  {
    id: 'volume_500k',
    title: 'Half Ton Hero',
    description: 'Lift 500,000 kg total volume',
    icon: '👑',
    unlockedAt: null,
    requirement: 500000,
    category: 'volume',
  },
  {
    id: 'streak_7',
    title: 'Week Warrior',
    description: 'Maintain a 7-day workout streak',
    icon: '📅',
    unlockedAt: null,
    requirement: 7,
    category: 'streak',
  },
  {
    id: 'streak_30',
    title: 'Monthly Machine',
    description: 'Maintain a 30-day workout streak',
    icon: '🗓️',
    unlockedAt: null,
    requirement: 30,
    category: 'streak',
  },
  {
    id: 'share_first',
    title: 'Social Butterfly',
    description: 'Share your first workout to the feed',
    icon: '📣',
    unlockedAt: null,
    requirement: 1,
    category: 'social',
  },
  {
    id: 'share_five',
    title: 'Community Star',
    description: 'Share 5 workouts to the feed',
    icon: '⭐',
    unlockedAt: null,
    requirement: 5,
    category: 'social',
  },
  {
    id: 'comp_first',
    title: 'Competitor',
    description: 'Complete your first daily competition',
    icon: '🎯',
    unlockedAt: null,
    requirement: 1,
    category: 'competition',
  },
  {
    id: 'comp_five',
    title: 'Championship Material',
    description: 'Complete 5 daily competitions',
    icon: '🥇',
    unlockedAt: null,
    requirement: 5,
    category: 'competition',
  },
];
